<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Kenya KML Example</title>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jquery-1.6.2.min.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() . '/js/mxn/mxn.js?(googlev3)'; ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() . '/js/timeline-1.2.js'; ?>"></script>
    <script src="<?php echo $this->basePath() . '/js/timemap.js'; ?>" type="text/javascript"></script>
    <script type="text/javascript">

function randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}

var tm;
var r = "[";
 
for (var x=0; x<20; x++) {
 if (x != 0) r+=',';
  r+='{';
  r+='title:"Item ' + x + '",';
  r+='start:"20013-08-15T15:52:01+0000",';
  r+='point:{lat:'+(50.9 + 10*Math.random()/<?php echo (float)getrandmax(); ?>)
       +',lon:' + (-1.3 + 10*Math.random()/<?php echo (float)getrandmax(); ?>)+'}';
  r+='}';
}
r+="]";

$(function() {
    
    tm = TimeMap.init({
        mapId: "map",               // Id of map div element (required)
        timelineId: "timeline",     // Id of timeline div element (required)
        options: {
            eventIconPath: "<?php echo $this->basePath() . '/img/'; ?>"
        },
      datasets: [
            {
                id: "events",
                title: "Event @SUSU",
                theme: "blue",
                // note that the lines below are now the preferred syntax
                type: "basic",
                options: {
                    items: [
                        {
                          "start" : "2013-11-12T19:00:00+00",
                          "end" : "2013-11-12T23:00:00+00",
                          "point" : {
                              "lat" : 50.933984,
                              "lon" : -1.397861
                           },
                          "title" : "Greek Society Meeting",
                          "options" : {
                            // set the full HTML for the info window
                            "infoHtml": "<div class='custominfostyle'><b>Greek Society</b> are socialising at the Bar with QUiz and Curry.</div>"
                          }
                        },
                        {
                          "start" : "2013-11-12T16:00:00+00",
                          "end" : "2013-11-12T22:00:00+00",
                          "point" : {
                              "lat" : 50.934288,
                              "lon" : -1.397738
                           },
                          "title" : "Krishna Society prayer meeting",
                          "options" : {
                            "infoHtml": "<div class='custominfostyle'><b>Krishna Society</b> are meditating at the Cube</div>",
                            "theme": "blue"
                          }
                        },
                        {
                          "start" : "2013-11-12T18:00:00+00",
                          "end" : "2013-11-12T22:00:00+00",
                          "point" : {
                              "lat" : 50.934176,
                              "lon" : -1.397662
                           },
                          "title" : "Day of Disney Movie Night",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Union Films</b> present the Day of Disney at the Box Office</div>",
                            "theme": "yellow"
                          }
                        },
												{
                          "start" : "2013-11-13T14:00:00+00",
                          "end" : "2013-11-13T20:00:00+00",
                          "point" : {
                              "lat" : 50.934203,
                              "lon" : -1.397512
                           },
                          "title" : "General Society Meet",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Asian Society</b> Annual Meet at Building 42</div>",
                            "theme": "blue"
                          }
                        },
												{
                          "start" : "2013-11-13T20:00:00+00",
                          "end" : "2013-11-13T23:30:00+00",
                          "point" : {
                              "lat" : 50.934176,
                              "lon" : -1.397662
                           },
                          "title" : "Harry Potter and the Deathly Hallows Part 1",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Union Films</b> present the Harry Potter at the Box Office</div>",
                            "theme": "yellow"
                          }
                        },
												{
                          "start" : "2013-11-14T16:00:00+00",
                          "end" : "2013-11-14T20:00:00+00",
                          "point" : {
                              "lat" : 50.93399,
                              "lon" : -1.396761
                           },
                          "title" : "Swimming meet",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Swimming Society</b> are meeting at Jubilee Sports Hall</div>",
                            "theme": "green"
                          }
                        },
												{
                          "start" : "2013-11-12T18:00:00+00",
                          "end" : "2013-11-12T22:00:00+00",
                          "point" : {
                              "lat" : 50.933984,
                              "lon" : -1.397861
                           },
                          "title" : "Quiz and Curry",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Philipino Society </b> are hosting a quiz and curry night at the Bridge Bar</div>",
                            "theme": "blue"
                          }
                        },
												{
                          "start" : "2013-11-13T18:00:00+00",
                          "end" : "2013-11-13T22:00:00+00",
                          "point" : {
                              "lat" : 50.934176,
                              "lon" : -1.397662
                           },
                          "title" : "Armageddon",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Union Films</b> present the Armageddon at the Box Office</div>",
                            "theme": "yellow"
                          }
                        },
												{
                          "start" : "2013-11-13T18:00:00+00",
                          "end" : "2013-11-13T22:00:00+00",
                          "point" : {
                              "lat" : 50.935941,
                              "lon" : -1.398671
                           },
                          "title" : "Diwali Festival: Lighting Diyas",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Asian Society</b> is celebrating Diwali at Turner Sims</div>",
                            "theme": "blue"
                          }
                        },
												{
                          "start" : "2013-11-17T16:00:00+00",
                          "end" : "2013-11-117T20:00:00+00",
                          "point" : {
                              "lat" : 50.93399,
                              "lon" : -1.396761
                           },
                          "title" : "Swimming meet",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Swimming Society</b> are meeting at Jubilee Sports Hall</div>",
                            "theme": "green"
                          }
                        },
												{
                          "start" : "2013-11-15T16:00:00+00",
                          "end" : "2013-11-15T20:00:00+00",
                          "point" : {
                              "lat" : 50.93399,
                              "lon" : -1.396761
                           },
                          "title" : "Swimming meet",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Swimming Society</b> are meeting at Jubilee Sports Hall</div>",
                            "theme": "green"
                          }
                        },
												{
                          "start" : "2013-11-16T16:00:00+00",
                          "end" : "2013-11-16T20:00:00+00",
                          "point" : {
                              "lat" : 50.93399,
                              "lon" : -1.396761
                           },
                          "title" : "Swimming meet",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Swimming Society</b> are meeting at Jubilee Sports Hall</div>",
                            "theme": "green"
                          }
                        },
												{
                          "start" : "2013-11-16T18:00:00+00",
                          "end" : "2013-11-16T22:00:00+00",
                          "point" : {
                              "lat" : 50.934176,
                              "lon" : -1.397662
                           },
                          "title" : "The Social Network",
                          "options" : {
                            // use the default title/description info window
                            "infoHtml": "<div class='custominfostyle'><b>Union Films</b> present the Social Network at the Box Office</div>",
                            "theme": "yellow"
                          }
                        }
                    ]
                }
            }
        ],
        bandIntervals: [
            Timeline.DateTime.HOUR, 
            Timeline.DateTime.DAY
        ]
    });
});
    </script>
    <link href="<?php echo $this->basePath() . '/css/examples.css';?>" type="text/css" rel="stylesheet"/>
    <style>
    div#timelinecontainer{ height: 150px; }
    div#mapcontainer{ height: 400px; }
    </style>
  </head>

  <body>
    <div id="help">
    <h1>Societies' Locator</h1>
    We're dynamically <a href='http://localhost/gslocator/public/simulator.php'>loading</a> data from a JSON service that takes start and end date parameters
    </div>
    <div id="timemap">
        <div id="timelinecontainer">
          <div id="timeline"></div>
        </div>
        <div id="mapcontainer">
          <div id="map"></div>
        </div>
    </div>
  </body>
</html>

