<?php echo $this->headScript() ->prependFile($this->basePath() . '/js/timeline-2.3.0.js') ; ?>
	<script type="text/javascript">

var tm;
$(function() {
    tm = TimeMap.init({
        mapId: "map",               // Id of map div element (required)
        timelineId: "timeline",     // Id of timeline div element (required) 
        options: {
            eventIconPath: "<?php echo $this->basePath() . '/img/'; ?>"
        },
        datasets: [
            {
                title: "Events in SUSU",
                theme: "green",
                type: "kml",     // Data to be loaded in KML - must be a local URL
                options: {
                    url: "<?php echo $this->basePath() . '/kenya.kml'; ?>" // KML file to load
                }
            }
        ],
        bandInfo: [
            {
               width:          "85%", 
               intervalUnit:   Timeline.DateTime.DAY, 
		       intervalPixels: 210
            },
            {
               width:          "15%", 
               intervalUnit:   Timeline.DateTime.WEEK, 
		       intervalPixels: 150,
               showEventText:  false,
               trackHeight:    0.2,
               trackGap:       0.2
            }
        ]
    });
});
    </script>
    

    <div id="help">
    <h1>Societies' Locator</h1>
    We're dynamically <a href='http://localhost/gslocator/public/simulator.php'>loading</a> data from a JSON service that takes start and end date parameters
    </div>
    <div id="timemap">
        <div id="timelinecontainer">
          <div id="timeline"></div>
        </div>
        <div id="mapcontainer">
          <div id="map"></div>
        </div>
    </div>
		 
<?php echo $this->inlineScript() 
						->prependFile($this->basePath() . '/js/timemap.js')
						->prependFile($this->basePath() . '/js/param.js')
						->prependFile($this->basePath() . '/js/loaders/xml.js')
						->prependFile($this->basePath() . '/js/loaders/kml.js')
						
						;?>
						