 <?php echo $this->inlineScript() 
						->prependFile($this->basePath() . '/js/jplist.min.js')
						->prependFile($this->basePath() . '/js/jlocator.min.js')
						->prependFile($this->basePath() . '/js/jquery-ui.js')
						;?>
<script>
			$('document').ready(function(){
				
				var api;
				
				$('#jlocator').jlocator({

                    mapTypeId: 'ROADMAP' //ROADMAP, SATELLITE, HYBRID, TERRAIN
					,jplist: {
						//panel controls
						control_types: {
							
							'range-slider-prices': {
							   class_name: 'RangeSlider'
							   ,options: {
								  
								  //jquery ui range slider
								  ui_slider: function($slider, $prev, $next){		
									 
									 $slider.slider({
										min: 0
										,max: 60
										,range: true
										,values: [0, 60]
										,slide: function(event, ui){									
										   $prev.text('$' + ui.values[0]);
										   $next.text('$' + ui.values[1]);
										}
									 });
								  }
								  
								  ,set_values: function($slider, $prev, $next){
									 
									 $prev.text('$' + $slider.slider('values', 0));
									 $next.text('$' + $slider.slider('values', 1));
								  }
							   }
							}
							
							,'range-slider-likes': {
							   class_name: 'RangeSlider'
							   ,options: {
								  
								  //jquery ui range slider
								  ui_slider: function($slider, $prev, $next){		
									 
									 $slider.slider({
										min: 0
										,max: 60
										,range: true
										,values: [0, 60]
										,slide: function(event, ui){									
										   $prev.text(ui.values[0] + ' Likes');
										   $next.text(ui.values[1] + ' Likes');
										}
									 });
								  }
								  
								  ,set_values: function($slider, $prev, $next){
									 
									 $prev.text($slider.slider('values', 0) + ' Likes');
									 $next.text($slider.slider('values', 1) + ' Likes');
								  }
							   }
							}
						}
					}
                });
			});
			</script>
		

<div id="main-content" class="box">
			<div class="center">
				<div id="page-content" class="box">

					<!-- tabs navigation -->
					
					
										
					<div class="box text-shadow">
						<h1 class="h1-30-normal left">Societies's Locator</h1>
					</div>
					
					
	
				<div class="box example-demo">
				
					<!-- STORE LOCATOR DEMO -->
					<div id="jlocator">
					
						<!-- panel -->
						<div class="panel" data-type="panel">
						
							<!-- controls -->
							<div class="controls" data-type="controls">

								<div class="box">

                                    <div class="reset-box left">
                                       <input
                                          type="button"
                                          class="jplist-btn"
                                          value="Reset"
                                          data-control-type="reset"
                                          data-control-name="reset"
                                          data-control-action="reset"
                                       />
                                    </div>

									<div 
										class="drop-down left" 
										data-control-type="drop-down" 
										data-control-name="sort" 
										data-control-action="sort"
										data-datetime-format="{month}/{day}/{year}"> <!-- {year}, {month}, {day}, {hour}, {min}, {sec} -->
										
										<ul>
											<li><span data-path="default">Sort by</span></li>
											<li><span data-path=".title" data-order="asc" data-type="text">Title A-Z</span></li>
											<li><span data-path=".title" data-order="desc" data-type="text">Title Z-A</span></li>
											<li><span data-path=".like" data-order="asc" data-type="number">Likes asc</span></li>
											<li><span data-path=".like" data-order="desc" data-type="number">Likes desc</span></li>
											<li><span data-path=".price" data-order="asc" data-type="number">Price asc</span></li>
											<li><span data-path=".price" data-order="desc" data-type="number">Price desc</span></li>
										</ul>
									</div>
									
								</div>
								
								<!-- autocomplete with a radius in miles -->
								<div 
									class="left"
									data-control-type="autocomplete-radius" 
									data-control-name="autocomplete-radius" 
									data-control-action="filter"
									data-units="miles"
									data-zoom="10"> <!-- units: miles, km -->
									
									<input 
										class="autocomplete"
										type="text"
										placeholder="Enter a location"
									/>
									
									<select class="distance jplist-select" style="margin-top: 6px;">
										<option value="1">1 Mile</option>
										<option value="5">5 Mile</option>
										<option value="10">10 Miles</option>
										<option value="30">30 Miles</option>
										<option value="50" selected="selected">50 Miles</option>
										<option value="100">100 Miles</option>
									</select>
								</div>
								
								<div class="box">
								
									<!-- checkbox filters -->
									<div 
										class="cb-group-filter left"
										data-control-type="checkbox-group-filter"
										data-control-action="filter"
										data-control-name="themes-art">
										
										<div class="cb">
											<input 			
												data-path=".art" 									
												id="art" 
												type="checkbox" 									
											/>
											<label for="art">Art</label>
										</div>										
									</div>
									
									<!-- checkbox filters -->
									<div 
										class="cb-group-filter left"
										data-control-type="checkbox-group-filter"
										data-control-action="filter"
										data-control-name="themes-history">
										
										<div class="cb">
											<input 
												data-path=".history"									
												id="history" 
												type="checkbox" />
											<label for="history">History</label>
										</div>									
									</div>
									
									<!-- checkbox filters -->
									<div 
										class="cb-group-filter left"
										data-control-type="checkbox-group-filter"
										data-control-action="filter"
										data-control-name="themes-science">
										
										<div class="cb">
											<input 
												data-path=".science"									
												id="science" 
												type="checkbox" />
											<label for="science">Science</label>
										</div>									
									</div>
								</div>
								
								<div class="box" style="margin-bottom: 10px;">
								
									<!-- range slider -->
									<div 
									   class="range-slider"
									   data-control-type="range-slider-prices" 
									   data-control-name="range-slider-prices" 
									   data-control-action="filter"
									   data-path=".price">
									   
									   <div class="value" data-type="prev-value"></div>
									   <div class="ui-slider" data-type="ui-slider"></div>
									   <div class="value" data-type="next-value"></div>
									</div>	
									
									<!-- range slider -->
									<div 
									   class="range-slider"
									   data-control-type="range-slider-likes" 
									   data-control-name="range-slider-likes" 
									   data-control-action="filter"
									   data-path=".like">
									   
									   <div class="value" data-type="prev-value"></div>
									   <div class="ui-slider" data-type="ui-slider"></div>
									   <div class="value" data-type="next-value"></div>
									</div>
								</div>
							</div>
							
							<!-- store list -->
							<div class="stores box" data-type="stores">
								
								<!-- place -->
								<div 
									data-type="store" 
									class="store box"
									data-latitude="50.936858" 
									data-longitude="-1.396053">
									<p class="art history science">
										<span class="title" data-type="title">Nuffield Theatre</span>,<br>
										<span data-type="address">32 University Road, University of Southampton Highfield Campus</span>,<br>
										<span data-type="city">Southampton</span>,<br>
										<span data-type="state">Hampshire</span>,<br>
										<!--span data-type="zipcode"></span><br/-->
										<span data-type="country">United Kingdom</span><br/>
										<span class="tags">Tags: Art</span><br/>
										Price: $<span class="price">15</span><br/>
										Likes: <span class="like">10</span>
									</p>
								</div>
								
								<!-- place -->
								<div 
									data-type="store" 
									class="store box"
									data-latitude="50.93626" 
									data-longitude="-1.39684">
									<p class="art">
										<span class="title" data-type="title">University Interchange</span>,<br>
										<span data-type="address">Highfield, Southampton Uni Interchange (S-bound)</span>,<br>
										<span data-type="city">University of Southampton Highfield Campus</span>,<br>
										<span data-type="state">Southampton</span> 
										<span data-type="zipcode">SO17 1BJ</span>,<br>
										<span data-type="country">United Kingdom</span><br/>
										<span class="tags">Tags: Art</span>
										Price: $<span class="price">25</span><br/>
										Likes: <span class="like">5</span>
									</p>
								</div>
								
								<!-- place -->
								<div 
									data-type="store" 
									class="store box"
									data-latitude="50.934166" 
									data-longitude="-1.396238">
									<p class="art science">
										<span class="title" data-type="title">SUSU-University of Southampton Student's Union</span>,<br>
										<span data-type="address">45 University Road</span>,<br>
										<span data-type="city">University of Southampton Highfield Campus</span>,<br>
										<span data-type="state">Hampshire</span>,<br>
										<!--span data-type="zipcode"></span>,<br/-->
										<span data-type="country">United Kingdom</span><br/>
										<span class="tags">Tags: Art, History</span>
										Price: $<span class="price">10</span><br/>
										Likes: <span class="like">20</span>
									</p>
								</div>
								
								<!-- place -->
								<div 
									data-type="store" 
									class="store box"
									data-latitude="50.933803" 
									data-longitude="-1.39947">
									<p class="art history">
										<span class="title" data-type="title">Geography and Enviroment</span>,<br>
										<span data-type="address">44 Chambarlain Road</span>,<br>
										<span data-type="city">Southampton</span>  
										<!--span data-type="state"></span>,<br/-->
										<span data-type="zipcode">SO17</span>,<br>
										<span data-type="country">United Kingdom</span>
										<span class="tags">Tags: Art, History</span>
										Price: $<span class="price">18</span><br/>
										Likes: <span class="like">30</span>
									</p>
								</div>
								
								<!-- place -->
								
							</div>
							
							<!-- no results -->
							<div class="box no-results" data-type="no-results">
								<p>No results found</p>
							</div>
							
						</div>
						
						<!-- map -->
						<div class="map" data-type="map"></div>
						
					</div>
					<!-- end of STORE LOCATOR-->
			
				</div>	
				</div>
			</div>
		</div>	